### PR TITLE
Server setup

### PR DESCRIPTION
**Pull request by danich1**
This PR sets up the server to generate the json file added in #1.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@danich1 I dont think I'm the appropriate person to review this, I'm not a Python or ML expert. Perhaps someone from the Greene Lab could review.

**Comment by staylorx** [comment]
I can take a look at it @danich1

**Comment by danich1** [comment]
>@danich1 I dont think I'm the appropriate person to review this, I'm not a Python or ML expert. Perhaps someone from the Greene Lab could review.

Ah @vincerubinetti  I was tagging you to see if I could get Steven or a backend developer to look into this PR. @staylorx beat me to the reply.

**Comment by danich1** [comment]
@staylorx Added you to repository access permissions. Feel free to review! Any access issues let me know.

**Review by staylorx — APPROVED** [review]
Thanks for the prework on the FastAPI! Looking forward to running the notebook.

**Pull request merged**
